[tools]
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2" 
rojo = "rojo-rbx/rojo@7.4.4"
lune = "filiptibell/lune@0.8.8"
wally = "UpliftGames/wally@0.3.2" 
stylua = "johnnymorganz/stylua@0.20.0"
selene = "Kampfkarren/selene@0.27.1"