[package]
name = "base_project/v1"
version = "0.0.1"
author = ["babypatrick100"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[server-dependencies]
instanceNetworkOwnerUtil = "bubshurb/instancenetworkownerutil@1.0.0"

[dependencies]
ZonePlus = "bubshurb/zoneplus@1"
Promise = "evaera/promise@4"
NumberSpinner = "boatbomber/numberspinner@0"
Timer = "sleitnick/timer@1"
Hover = "bubshurb/hover@1"
Loader = "sleitnick/loader@2" 
WindShake = "boatbomber/windshake@2"
Signal = "sleitnick/signal@2"
Sift = "csqrl/sift@0" 
DistortionScreenRain = "boatbomber/distortion-screen-rain@1"
Input = "sleitnick/input@2"
TopbarPlus = "virtualbutfake/topbarplus@3.0.2"
Component = "bubshurb/component@1"
Trove = "sleitnick/trove@1"
WaitFor = "sleitnick/wait-for@1"
SnapDragon = "vorlias/snapdragon@2"
Matcher = "bubshurb/matcher@1"
ValueMultiplier = "bubshurb/valuemultiplier@1"
CustomAnimator = "bubshurb/customanimator@1"
evLightning = "bubshurb/evlightning@1"
Property = "bubshurb/property@2"
rain = "bubshurb/rain@1"
instanceTagUtil = "bubshurb/instancetagutil@1"
windLines = "bubshurb/windlines@1"
throttleUtil = "bubshurb/throttleutil@1"
instancePropertyUtil = "bubshurb/instanceutil@1" 
perInstanceDataCacheUtil = "bubshurb/perinstancedatacacheutil@1"
network = "bubshurb/network@2" 
numberUtil = "bubshurb/numberutil@1" 
dateUtil = "bubshurb/dateutil@1"
soundUtil = "bubshurb/soundutil@1"
coreGuiUtil = "bubshurb/coreguiutil@1"
playerPolicyInfoUtil = "bubshurb/playerpolicyinfoutil@1"
debugLoggerUtil = "bubshurb/debugloggerutil@1" 
serializerUtil = "bubshurb/serializerutil@1"
positionUtil = "bubshurb/positionutil@1"
schedulerUtil = "bubshurb/schedulerutil@1" 
colorSequenceUtil = "bubshurb/colorsequenceutil@1"
instanceTroveUtil = "bubshurb/instancetroveutil@1" 
stringUtil = "bubshurb/stringutil@1"
toolUtil = "bubshurb/toolutil@1"
playerUtil = "bubshurb/playerutil@1"
playersUtil = "bubshurb/playersutil@1"
playerCharacterUtil = "bubshurb/playercharacterutil@1"
marketPlaceServiceUtil = "bubshurb/marketplaceserviceutil@1" 
badgeServiceUtil = "bubshurb/badgeserviceutil@1"
promiseCleanupUtil = "bubshurb/promisecleanuputil@1" 
colorUtil = "bubshurb/colorutil@1"
contextActionServiceUtil = "bubshurb/contextactionserviceutil@1"
playerEventsUtil = "bubshurb/playereventsutil@1"
instanceAttributeUtil = "bubshurb/instanceattributeutil@1" 
instanceTrackerUtil = "bubshurb/instancetrackerutil@1"
rbxScriptSignalUtil = "bubshurb/rbxscriptsignalutil@1"
numberUnitUtil = "bubshurb/numberunitutil@1"
queryUtil = "bubshurb/queryutil@1"
lightingUtil = "bubshurb/lightingutil@1"
viewportFrameUtil = "bubshurb/viewportframeutil@1"
timeFormatUtil = "bubshurb/timeformatutil@1"
weldConstraintUtil = "bubshurb/weldconstraintutil@1"
basePartSizeUtil = "bubshurb/basepartresizeutil@1"
instanceTranslationUtil = "bubshurb/instancetranslationutil@1"
numberStringUtil = "bubshurb/numberstringutil@1"
robuxConversionUtil = "bubshurb/robuxconversionutil@1"
orderUtil = "bubshurb/orderutil@1"
seatUtil = "bubshurb/seatutil@1"
propertyUtil = "bubshurb/propertyutil@1"
playerCharacterAccessoryUtil = "bubshurb/playercharacteraccessoryutil@1"
infoTypeUtil = "bubshurb/infotypeutil@1"
playerHumanoidUtil = "bubshurb/playerhumanoidutil@1"
soundInitializerUtil = "bubshurb/soundinitializerutil@1.0.0"
clientMovementInputUtil = "bubshurb/clientmovementinpututil@1"
instancePropertyUtil = "bubshurb/instancepropertyutil@1.0.0"
basePartUtil = "bubshurb/basepartutil@1"